### ISSUE TITLE
1月14号使用该程序已经跳的不准了

### ISSUE THREAD

**Issue by xmm228** [ksky521/wechat-jump-game-hack#6]
每次跳的不是中心，而且在一些地方直接跳出，好像是部分方块的计算出了问题，导致跳的不准了

**Comment by ksky521** [comment]
可能是用的手机型号跟我不一样，你看下server端jump.js里面的系数调整下看看，最近也没留意14号之后的变化，欢迎继续按照我的思路研究，然后提PR
